# syntax=docker/dockerfile:1.7
FROM maven:3.9.8-eclipse-temurin-21 AS build
WORKDIR /app

COPY pom.xml ./
COPY src ./src
RUN mvn -q -DskipTests -Dspring-boot.build-image.skip=true clean package


FROM eclipse-temurin:21-jre-alpine AS runtime
WORKDIR /app

COPY --from=build /app/target/*.jar /app/maintenance.jar
ENV JAVA_TOOL_OPTIONS="-Dserver.port=8085"
EXPOSE 8085
ENTRYPOINT ["java", "-jar", "/app/maintenance.jar"]
